global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'openclassifier'
    replica: 'prometheus-1'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # OpenClassifier application metrics
  - job_name: 'openclassifier'
    static_configs:
      - targets: ['openclassifier:8000', 'openclassifier_replica:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis_exporter:9121']
    scrape_interval: 15s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 15s

  # Custom application health checks
  - job_name: 'openclassifier-health'
    static_configs:
      - targets: ['openclassifier:8000', 'openclassifier_replica:8000']
    metrics_path: '/health'
    scrape_interval: 30s
    scrape_timeout: 10s

  # NGINX metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx_exporter:9113']
    scrape_interval: 15s

storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

remote_write:
  - url: "http://prometheus:9090/api/v1/write"
    queue_config:
      capacity: 10000
      max_samples_per_send: 5000
      batch_send_deadline: 10s 